aws_access_key_id     = "your_access_key_id"
aws_secret_access_key = "your_secret_access_key"
aws_default_region    = "eu-central-1"
bucket_name           = "example-terraform-bucket-123"
resource_group_name   = "weather-app"
vm_admin_username     = "ubuntu"
ssh_public_key        = "ssh-rsa AAAA..."
