key_name             = "your-key-name"
aws_access_key_id    = "your-access-key"
aws_secret_access_key = "your-secret-key"
aws_default_region   = "eu-central-1"
bucket_name          = "your-unique-bucket-name-2025"
resource_group_name  = "my-resource-group"
vm_admin_username    = "ubuntu"
ssh_public_key       = "ssh-rsa AAAA...."
