resource_group_name     = "weather-app"
resource_group_location = "centralindia"
ssh_public_key          = "your-actual-ssh-key"
vm_admin_username = "sebastian"
vm_admin_password = "Sebastian123456^%$#@!"
