apiVersion: v1
kind: Service
metadata:
  name: weather-app-service
spec:
  selector:
    app: weather-app
  ports:
    - protocol: TCP
      port: 5000       # Change this from 80 to 5000
      targetPort: 5000
      nodePort: 30007  # Choose a free port in range 30000-32767
  type: NodePort       # Change from ClusterIP to NodePort
