---
- name: Install NGINX
  apt:
    name: nginx
    state: present
    update_cache: yes
  become: true

- name: Create NGINX configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart NGINX
  become: true

- name: Create load balancer configuration
  template:
    src: load-balancer.conf.j2
    dest: /etc/nginx/conf.d/load-balancer.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart NGINX
  become: true

- name: Ensure NGINX service is running
  systemd:
    name: nginx
    state: started
    enabled: yes
  become: true
