name: Terraform apply
run-name: ${{ github.actor }} is deploying on AWS 🚀
on:
  push:
    branches: 
      feature/aws-s3-module
jobs:
  Deploy-AWS-Ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_MARIUS }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_MARIUS }}
          aws-region: eu-central-1
      - name: Deploy Infrastructure
        run: |
          terraform init
      - run: |
          terraform apply -auto-approve
